version: '3.9'

services:
  hummingbot:
    container_name: hummingbot
    image: hummingbot/hummingbot:latest
    volumes:
      - ./hummingbot/conf:/conf
      - ./hummingbot/logs:/logs
      - ./hummingbot/data:/data
      - ./hummingbot/scripts:/scripts
    environment:
      - CONFIG_PASSWORD=${CONFIG_PASSWORD}
      - CONFIG_FILE_NAME=${CONFIG_FILE_NAME}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host

  # Future: Add our ML service here
  # ml-service:
  #   build: .
  #   command: python src/main.py
  #   volumes:
  #     - ./src:/app/src
  #     - ./logs:/app/logs
  #   environment:
  #     - POLYGON_API_KEY=${POLYGON_API_KEY}
  #     - SUPABASE_URL=${SUPABASE_URL}
  #     - SUPABASE_KEY=${SUPABASE_KEY}
  #   depends_on:
  #     - hummingbot
  #   restart: unless-stopped
