version: '3.8'

services:
  hummingbot:
    image: hummingbot/hummingbot:latest
    container_name: crypto-tracker-hummingbot
    volumes:
      - ./hummingbot/conf:/conf
      - ./hummingbot/logs:/logs
      - ./hummingbot/data:/data
      - ./hummingbot/scripts:/scripts
      - ./hummingbot/certs:/certs
    environment:
      - HUMMINGBOT_MODE=${HUMMINGBOT_MODE:-paper_trade}
      - EXCHANGE=${HUMMINGBOT_EXCHANGE:-kraken}
      - STRATEGY=${HUMMINGBOT_STRATEGY:-ml_signal_strategy}
      - CONFIG_PASSWORD=${CONFIG_PASSWORD:-password}
    networks:
      - crypto-network
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: crypto-tracker-postgres
    environment:
      POSTGRES_DB: hummingbot_db
      POSTGRES_USER: hummingbot
      POSTGRES_PASSWORD: ${DB_PASSWORD:-hummingbot_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crypto-network
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: crypto-tracker-redis
    networks:
      - crypto-network
    ports:
      - "6380:6379"  # Different port to avoid conflicts
    restart: unless-stopped

networks:
  crypto-network:
    driver: bridge

volumes:
  postgres_data: