# nixpacks.toml
[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[variables]
PYTHONUNBUFFERED = "1"

[start]
cmd = "echo 'Starting services...'"
