[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "freqtrade trade --config /freqtrade/user_data/config.json --strategy ChannelStrategyV1 --dry-run"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
